logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "erik.river@gmail.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik-network"
  domain = "docker.mysite.com"
  watch = true
  swarmMode = false

[api]
  entryPoint = "traefik"
  dashboard = true
