version: '3.4'
services:
  traefik:
    image: traefik:1.7.12-alpine
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./conf/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./conf/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent -f https://localhost:9200/_cluster/health -u admin:admin --insecure || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    networks:
      - odfe-network

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    container_name: odfe-kibana
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
      SERVER_NAME: kibana.mysite.com
    networks:
      - traefik-network
      - odfe-network
    labels:
      - "traefik.enable=true"
      - "traefik.web.port=5601"
      - "traefik.web.frontend.rule=Host:kibana.mysite.com"
      - "traefik.web.backend.healthcheck.path=/api/status"
      - "traefik.web.backend.healthcheck.interval=10s"
    depends_on:
      - odfe-node1
      - odfe-node2
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent -f http://localhost:5601/api/status -u admin:admin || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  odfe-data1:
  odfe-data2:

networks:
  traefik-network:
    external: true
  odfe-network:
    external: false
